name: Build wrap-logger

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Copy other required files
      run: |
        cp .gitignore wrap_logger/.gitignore
        cp README.md wrap_logger/README.md
        cp LICENSE.md wrap_logger/LICENSE.md
    - uses: actions/upload-artifact@v3
      with:
        name: 'wrap-logger'
        path: wrap_logger
